# Generated by Django 4.2.7 on 2024-02-15 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=30, verbose_name='Apellidos')),
                ('telefono', models.CharField(max_length=20, verbose_name='Telefono')),
                ('email', models.EmailField(max_length=20, verbose_name='Email')),
                ('cedula', models.CharField(max_length=20, verbose_name='Cedula')),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('1', 'Inactivo')], max_length=20, verbose_name='Estado:')),
            ],
        ),
    ]
