# Generated by Django 4.2.7 on 2024-02-15 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_customers_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='email',
            field=models.EmailField(default='prueba@prueba.com', max_length=30, verbose_name='email'),
        ),
    ]
