# Generated by Django 3.2.24 on 2024-02-18 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_customers_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customers',
            options={'verbose_name_plural': 'Lista de Clientes'},
        ),
    ]
