# Generated by Django 4.2.7 on 2024-02-14 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField()),
                ('total_venta_pesos', models.FloatField(verbose_name='total venta en pesos: ')),
            ],
        ),
    ]
