# Generated by Django 4.2.7 on 2024-02-20 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_producto_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='tipo',
            field=models.CharField(choices=[('1', 'Gas'), ('2', 'Tanque Estacionario'), ('3', 'Otro')], max_length=20),
        ),
    ]
