# Generated by Django 4.2.7 on 2024-02-21 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0004_alter_customers_options'),
        ('employes', '0002_auto_20240218_1825'),
        ('product', '0003_alter_producto_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gastos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField()),
                ('descripcion', models.TextField(max_length=100, verbose_name='Descripcion')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
            options={
                'verbose_name_plural': 'Egresos',
            },
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(editable=False)),
                ('modified', models.DateTimeField(editable=False)),
                ('total_venta_pesos', models.DecimalField(decimal_places=2, max_digits=20)),
                ('total_venta_producto', models.DecimalField(decimal_places=2, max_digits=20)),
                ('metodo_pago', models.CharField(choices=[('1', 'Efectivo'), ('2 Bancaria', 'Transferencia Bancaria'), ('3', 'NEQUI'), ('4', 'Daviplata'), ('5', 'Otro')], max_length=50, verbose_name='metodo de pago')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customers')),
                ('empleado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employes.empleado')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.producto')),
            ],
            options={
                'verbose_name_plural': 'Ventas',
            },
        ),
    ]
