# Generated by Django 4.2.7 on 2024-02-15 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0002_alter_customers_id'),
        ('employes', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gastos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField()),
                ('descripcion', models.TextField(max_length=100, verbose_name='Descripcion')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(editable=False)),
                ('modified', models.DateTimeField(editable=False)),
                ('total_venta_pesos', models.DecimalField(decimal_places=2, max_digits=20)),
                ('total_venta_producto', models.DecimalField(decimal_places=2, max_digits=20)),
                ('metodo_pago', models.CharField(choices=[('Efectivo', 'Efectivo'), ('Transferencia Bancaria', 'Transferencia Bancaria'), ('NEQUI', 'NEQUI'), ('Daviplata', 'Daviplata'), ('Otro', 'Otro')], max_length=50, verbose_name='metodo de pago')),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customers')),
                ('id_empleado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employes.empleado')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.producto')),
            ],
        ),
    ]
