# Generated by Django 3.2.24 on 2024-02-18 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gastos',
            options={'verbose_name_plural': 'Egresos'},
        ),
        migrations.AlterModelOptions(
            name='ventas',
            options={'verbose_name_plural': 'Ventas'},
        ),
    ]
